# Generated by Django 4.0.3 on 2022-04-09 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_rename_url_post_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='photo',
            new_name='image',
        ),
    ]
