# Generated by Django 4.0.3 on 2022-04-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_rename_photo_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=300)),
                ('link', models.URLField(max_length=500)),
            ],
        ),
    ]
