# Generated by Django 4.0.3 on 2022-04-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0004_awards'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_caption', models.CharField(blank=True, max_length=310)),
                ('Post_link', models.URLField(max_length=501)),
                ('Post_image', models.ImageField(default='no-image', upload_to='images/')),
                ('pub_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(max_length=501),
        ),
    ]
